export enum INPUT_TYPE {
  Text = "Text",
  Dropdown = "Dropdown",
  MultiSelect = "Multi Select",
  ListBox = "List Box",
  Date = "Date",
}

export const SystemFields: { [key: string]: string } = {
  Username: INPUT_TYPE.Text,
  Password: INPUT_TYPE.Text,
  "Confirm Password": INPUT_TYPE.Text,
  "Employee Name": INPUT_TYPE.ListBox,
  Nickname: INPUT_TYPE.Text,
  "Employee Id": INPUT_TYPE.Text,
  "Other Id": INPUT_TYPE.Text,
  "Driver's License Number": INPUT_TYPE.Text,
  "License Expiry Date": INPUT_TYPE.Date,
  "SSN Number": INPUT_TYPE.Text,
  "SIN Number": INPUT_TYPE.Text,
  Nationality: INPUT_TYPE.Dropdown,
  "Marital Status": INPUT_TYPE.Dropdown,
  "Date of Birth": INPUT_TYPE.Date,
  Gender: INPUT_TYPE.MultiSelect,
  "Military Service": INPUT_TYPE.Text,
  Smoker: INPUT_TYPE.MultiSelect,
  "Employment Status": INPUT_TYPE.Dropdown,
  "PIM Status": INPUT_TYPE.MultiSelect,
  Include: INPUT_TYPE.Dropdown,
  "Supervisor Name": INPUT_TYPE.ListBox,
  "Job Title": INPUT_TYPE.Dropdown,
  "Sub Unit": INPUT_TYPE.Dropdown,
  "Show Leave with Status": INPUT_TYPE.Dropdown,
  "Leave Type": INPUT_TYPE.Dropdown,
  "From Date": INPUT_TYPE.Date,
  "To Date": INPUT_TYPE.Date,
  Vacancy: INPUT_TYPE.Dropdown,
  "Hiring Manager": INPUT_TYPE.Dropdown,
  "CandiDate Name": INPUT_TYPE.ListBox,
  "CandiDate Status": INPUT_TYPE.Dropdown,
  "Date of Application": INPUT_TYPE.Date,
  "Report Name": INPUT_TYPE.Text,
  "Selection Criteria": INPUT_TYPE.Dropdown,
  "Select Display Field Group": INPUT_TYPE.Dropdown,
  "Select Display Field": INPUT_TYPE.Dropdown,
  Location: INPUT_TYPE.Dropdown,
};
