export enum INPUT_TYPE {
  TEXT = "Text",
  DROPDOWN = "Dropdown",
  MULTI_SELECT = "Multi Select",
  LIST_BOX = "List Box",
  DATE = "Date",
}

export const SystemFields: { [key: string]: string } = {
  Username: INPUT_TYPE.TEXT,
  Password: INPUT_TYPE.TEXT,
  "Confirm Password": INPUT_TYPE.TEXT,
  "Employee Name": INPUT_TYPE.LIST_BOX,
  Nickname: INPUT_TYPE.TEXT,
  "Employee Id": INPUT_TYPE.TEXT,
  "Other Id": INPUT_TYPE.TEXT,
  "Driver's License Number": INPUT_TYPE.TEXT,
  "License Expiry Date": INPUT_TYPE.DATE,
  "SSN Number": INPUT_TYPE.TEXT,
  "SIN Number": INPUT_TYPE.TEXT,
  Nationality: INPUT_TYPE.DROPDOWN,
  "Marital Status": INPUT_TYPE.DROPDOWN,
  "Date of Birth": INPUT_TYPE.DATE,
  Gender: INPUT_TYPE.MULTI_SELECT,
  "Military Service": INPUT_TYPE.TEXT,
  Smoker: INPUT_TYPE.MULTI_SELECT,
  "Employment Status": INPUT_TYPE.DROPDOWN,
  "PIM Status": INPUT_TYPE.MULTI_SELECT,
  Include: INPUT_TYPE.DROPDOWN,
  "Supervisor Name": INPUT_TYPE.LIST_BOX,
  "Job Title": INPUT_TYPE.DROPDOWN,
  "Sub Unit": INPUT_TYPE.DROPDOWN,
  "Show Leave with Status": INPUT_TYPE.DROPDOWN,
  "Leave Type": INPUT_TYPE.DROPDOWN,
  "From Date": INPUT_TYPE.DATE,
  "To Date": INPUT_TYPE.DATE,
  Vacancy: INPUT_TYPE.DROPDOWN,
  "Hiring Manager": INPUT_TYPE.DROPDOWN,
  "Candidate Name": INPUT_TYPE.LIST_BOX,
  "Candidate Status": INPUT_TYPE.DROPDOWN,
  "Date of Application": INPUT_TYPE.DATE,
};
